### ISSUE TITLE
Images in blog posts

### ISSUE THREAD

**Issue by skel84** [konstantinmuenster/gatsby-starter-portfolio-minimal-theme#11]
Hi,

I'm trying to insert an image in a blog post, but it doesn't show up:

```
[...]
![Alt text](../../images/image.png)

or

<img src="../../images/image.png" alt="Alt text" />

[...]
```

Do you have an idea why this happens?

**Comment by konstantinruge** [comment]
Hey @skel84 ! Thanks for opening the issue. Actually, I haven't added image support for blog posts yet 😅 If you like, feel free to contribute to the [`gatsby-theme-portfolio-minimal`](https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal) package via PR. I guess we only need to a Gatsby plugin to transform images ([this one](https://www.gatsbyjs.com/plugins/gatsby-remark-images/)) and add some styling.

Otherwise, I will add it if I find time for it 👍️

**Comment by sorrel** [comment]
I was wondering if a solution would be to change the .md files to be .mdx files and then use **gatsby-plugin-mdx** - or does the architecture of the portfolio mean this would be too great a change?

**Comment by konstantinruge** [comment]
@sorrel this would probably work too 👍 I might find some time to work on the implementation this week

**Comment by sorrel** [comment]
@konstantinmuenster that would be wonderful! I am new to Gatsby, and have been trying to work out how to do it without success so far...

**Comment by konstantinruge** [comment]
@sorrel @skel84 I just released a new version that contains support for markdown images ☺️ You can just upgrade to [v3.3.0](https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/releases/tag/v3.3.0). Let me know if you have any issues or improvements!
